[package]
name = "cs"
version = "0.1.0"
authors = ["Sumeet Agarwal <sumeet.a@gmail.com>"]
edition = "2018"

[features]
default = ["glium", "glutin", "imgui", "imgui-sys", "imgui-glium-renderer", "pyo3"]
javascript = ["yew", "stdweb"]

[dependencies]
objekt = "0.1.1"
debug-cell = "0.1.1"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
erased-serde = "0.3.6"
failure = "0.1.2"
uuid = { version = "0.7.1", features = ["serde", "v4"] }
lazy_static = "1.1.0"
itertools = "0.7.8"
indexmap = "1.0.2"

pyo3 = { version = "0.4.1", optional = true }
glium = { version = "0.22", default-features = true, optional = true }
glutin = { version = "0.18", optional = true }
imgui = { version = "0.0.21", optional = true }
imgui-sys = { version = "0.0.21", optional = true }
imgui-glium-renderer = { version = "0.0.21", optional = true }

yew = { git = "https://github.com/DenisKolodin/yew", optional = true }
stdweb = { version = "0.4.9", optional = true }
