#!/bin/bash
set -e

cargo install diesel
diesel migration run
./scripts/gen-env.py > ./static/env.js

cargo install cargo-web || echo "cargo-web already installed"
cargo web build --release --target=wasm32-unknown-unknown --package editor

cp target/wasm32-unknown-unknown/release/editor.wasm ./static/editor.wasm
cp target/wasm32-unknown-unknown/release/editor.js ./static/editor.js
